"""empty message

Revision ID: 0480159959ab
Revises: 7b9c5dd2e39c
Create Date: 2019-04-19 20:21:34.601797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0480159959ab'
down_revision = '7b9c5dd2e39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('gear_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gear_id'], ['gear_item.gear_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['club_member.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'gear_id')
    )
    op.create_table('sleeping_bag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('bag_type', sa.String(), nullable=True),
    sa.Column('temp_rating', sa.Integer(), nullable=True),
    sa.Column('insulation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['gear_item.gear_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleeping_bag')
    op.drop_table('reservations')
    # ### end Alembic commands ###
