"""empty message

Revision ID: 5466cf9b41a8
Revises: 
Create Date: 2019-04-19 21:29:30.232825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5466cf9b41a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gear_item',
    sa.Column('gear_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('best_use', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('gear_id')
    )
    op.create_table('reservations',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('gear_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gear_id'], ['gear_item.gear_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['club_member.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'gear_id')
    )
    op.create_table('sleeping_bag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('bag_type', sa.String(), nullable=True),
    sa.Column('temp_rating', sa.Integer(), nullable=True),
    sa.Column('insulation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['gear_item.gear_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleeping_bag')
    op.drop_table('reservations')
    op.drop_table('gear_item')
    op.drop_table('club_member')
    # ### end Alembic commands ###
